# ну вот тут вот собсна напишу файлик
services:
  redis:
    image: redis

  rocketcounter:
    image: rotorocloud/rocket-counter
    ports:
      # - "8085:5000"
      - "0:5000"
    depends_on:
      - redis
# и собсна написал ;)